name: escribo
description: A Flutter package to easily create and customize text-based stories, similar to Instagram statuses. Choose fonts, backgrounds, and export the result as an image.
version: 1.0.1
homepage: https://github.com/DelaRosaJose/escribo-flutter 
repository: https://github.com/DelaRosaJose/escribo-flutter
issue_tracker: https://github.com/DelaRosaJose/escribo-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # For capturing the widget as an image
  screenshot: ^3.0.0 

  # To allow developers to easily use Google Fonts
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0